# Generated by Django 2.2 on 2020-12-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('videocard', models.CharField(max_length=128)),
                ('ram', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=128)),
                ('mother_board', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
