# Generated by Django 2.2 on 2020-10-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('prise', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('wheel_material', models.CharField(max_length=128)),
                ('diameter_mm', models.IntegerField(default=0)),
                ('thickness', models.CharField(max_length=128)),
                ('rigidity', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'Колеса',
                'verbose_name_plural': 'Колеса',
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('prise', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=128)),
                ('base_material', models.CharField(max_length=128)),
                ('axle', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'Подвески',
                'verbose_name_plural': 'Подвески',
            },
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('prise', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=128)),
                ('accuracy_class', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'Подшипники',
                'verbose_name_plural': 'Подшипники',
            },
        ),
    ]
