# Generated by Django 2.2 on 2020-10-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201023_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('prise', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=128)),
                ('wide', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'Дека',
                'verbose_name_plural': 'Дека',
            },
        ),
    ]
